#!/usr/bin/env python
import sys
import warnings
import random 

from datetime import datetime

from crew_test.teacher.crew import TeacherCrew
from crew_test.appraiser.crew import AppraiserCrew
from crew_test.image_reader.crew import ImageReaderCrew

warnings.filterwarnings("ignore", category=SyntaxWarning, module="pysbd")

def run():
    teacher = TeacherCrew().crew()
    appraiser = AppraiserCrew().crew()
    image_reader = ImageReaderCrew().crew()

    inputs = {
        'school_year': 'sexto ano',
        'question': '''
            Encontre a área da figura na imagem?
        ''',
        'correct_answer': '''
        ''',
        'max_number_of_tips': 4,
        'tips': '', # Tips will be generated by the teacher crew
        'image_description': '' # Image description will be generated by the image reader crew
    }

    inputs['image_description'] = image_reader.kickoff(inputs={"image_url": "https://res.cloudinary.com/dzgzxcisn/image/upload/v1739018890/questions/Equa%C3%A7%C3%A3o.png"}).raw
    inputs['tips'] = teacher.kickoff(inputs=inputs).raw
    ans = appraiser.kickoff(inputs=inputs) # Use this variable for saving the results 