#!/usr/bin/env python
import sys
import warnings
import random 

from datetime import datetime

from crew_test.teacher.crew import TeacherCrew
from crew_test.appraiser.crew import AppraiserCrew

warnings.filterwarnings("ignore", category=SyntaxWarning, module="pysbd")

def run():
    """
    Run the crew.
    """

    teacher = TeacherCrew().crew()
    appraiser = AppraiserCrew().crew()

    inputs = {
        'school_year': 'sexto ano',
        'question': '''
            Uma farmácia vende comprimidos em caixas com
            12, ao custo de 40 reais por caixa, ou em caixas com 8, ao
            custo de 25 reais por caixa. Paulo comprou exatamente
            28 comprimidos. Quanto ele gastou, em reais, nessa
            compra?
        ''',
        'correct_answer': '''
            Paulo comprou 28 comprimidos, em caixas com quantidades de 8 ou de 12 comprimidos cada. A única
            forma de Paulo fazer essa compra é com uma caixa de 12 comprimidos e duas caixas com 8 comprimidos. Logo, ele
            gastou 1 * 40 = 40 reais na caixa com 12 comprimidos mais 2 * 25 = 50 reais nas duas caixas com 8 comprimidos,
            totalizando 40 + 50 = 90 reais gastos nessa compra.
        ''',
        'tips': '' # Tips will be generated by the teacher crew
    }

    inputs['tips'] = teacher.kickoff(inputs=inputs).raw
    ans = appraiser.kickoff(inputs=inputs) # Use this variable for saving the results 